spring:
  application:
    name: GetUser
  cloud:
    zookeeper:
      connect-string: 192.168.126.10:2181,192.168.126.11:2181,192.168.126.12:2181
server:
  port: 8083
logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN
