spring:
  application:
    name: UserDemo
  cloud:
    zookeeper:
      connect-string: 192.168.126.10:2181,192.168.126.11:2181,192.168.126.12:2181
      discovery:
        enabled: true
server:
  port: 8081
endpoints:
  restart:
    enabled: true
logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN
